### ISSUE TITLE
Error 404 on parts 2 & 3

### ISSUE THREAD

**Issue by AlSch092** [0xSh4dy/learning_llvm#2]
Hi, thanks for your blog posts.

Just a heads up that the links to parts 2 and 3 give a 404 error off this github repo, it seems they work instead by visiting your blog manually and finding the same posts.

Cheers,
Alsch092

**Comment by 0xSh4dy** [comment]
Hi @AlSch092 
Thanks for letting me know. I’ve updated the README, and the links should now work.
